# Generated by Django 4.2.1 on 2023-06-02 20:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("Voter", "0002_alter_voter_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
