# Generated by Django 4.2.2 on 2023-06-06 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Voter", "0003_alter_voter_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="journalist_certificate",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
